### ISSUE TITLE
Possible Windows version?

### ISSUE THREAD

**Issue by bluewalk** [hadleyrich/mosquitto-auth-plugin-http#1]
Really like your simplistic setup of this plugin. Is it possible to also have a precompiled binary for Windows?

**Comment by hadleyrich** [comment]
Hi. Thanks for your kind comment. Unfortunately I don't have access to Windows to be able to try it out or compile it.

**Comment by bluewalk** [comment]
That's too bad. Is there a way to cross compile it from Linux or somehow on Windows so I can give it a shot?

**Comment by hadleyrich** [comment]
I'm not sure sorry, I don't know Windows.

**Comment by bluewalk** [comment]
Thanks anyway :+1:
